# Generated by Django 6.0.1 on 2026-02-07 21:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fxrate_alter_sale_options_product_price_usd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.TextField(blank=True, default='', verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_id_doc',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Número de cédula / RIF'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PAGO_MOVIL', 'Pago móvil'), ('PUNTO', 'Punto'), ('DIVISAS', 'Divisas'), ('USDT', 'USDT')], db_index=True, default='', max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60, verbose_name='Referencia (Pago móvil / Punto)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='subtotal_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.16'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_method', 'created_at'], name='inventory_s_payment_cd2171_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_reference'], name='inventory_s_payment_c72f15_idx'),
        ),
    ]
